using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Signalynx.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class SignalynxGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor DuplicateHandler = new(
        "SLX001",
        "Duplicate Signalynx handler",
        "Multiple handlers implement single-handler contract '{0}'",
        "Signalynx",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntaxContext, _) => GetCandidate(syntaxContext))
            .Where(static candidate => candidate is not null)
            .Collect();

        context.RegisterSourceOutput(candidates, static (productionContext, items) =>
            Generate(productionContext, items!));
    }

    private static HandlerCandidate? GetCandidate(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type ||
            type.IsAbstract ||
            type.IsGenericType)
        {
            return null;
        }

        var registrations = ImmutableArray.CreateBuilder<Registration>();
        foreach (var contract in type.AllInterfaces)
        {
            var definition = contract.OriginalDefinition;
            if (IsHandlerInterface(definition))
            {
                registrations.Add(new Registration(
                    contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    IsMultiHandler(definition)));
            }
        }

        return registrations.Count == 0
            ? null
            : new HandlerCandidate(
                type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                registrations.ToImmutable(),
                declaration.Identifier.GetLocation());
    }

    private static void Generate(
        SourceProductionContext context,
        ImmutableArray<HandlerCandidate?> candidates)
    {
        var handlers = candidates
            .Where(static candidate => candidate is not null)
            .Select(static candidate => candidate!)
            .GroupBy(static candidate => candidate.ImplementationType, StringComparer.Ordinal)
            .Select(static group => group.First())
            .OrderBy(static candidate => candidate.ImplementationType, StringComparer.Ordinal)
            .ToArray();

        var singleRegistrations = handlers
            .SelectMany(static handler => handler.Registrations.Select(registration => (handler, registration)))
            .Where(static entry => !entry.registration.AllowsMultiple &&
                                   !entry.registration.ServiceType.Contains("PipelineBehavior"))
            .GroupBy(static entry => entry.registration.ServiceType, StringComparer.Ordinal);

        foreach (var group in singleRegistrations)
        {
            if (group.Skip(1).Any())
            {
                foreach (var duplicate in group)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DuplicateHandler,
                        duplicate.handler.Location,
                        group.Key));
                }
            }
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Microsoft.Extensions.DependencyInjection");
        source.AppendLine("{");
        source.AppendLine("    public static class SignalynxGeneratedServiceCollectionExtensions");
        source.AppendLine("    {");
        source.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSignalynxGenerated(");
        source.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services,");
        source.AppendLine("            global::System.Action<global::Signalynx.SignalynxOptions>? configure = null)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");
        source.AppendLine("            return global::Signalynx.ServiceCollectionExtensions.AddSignalynx(");
        source.AppendLine("                services,");
        source.AppendLine("                SignalynxGeneratedHandlerMap.Descriptors,");
        source.AppendLine("                configure);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddSignalynxGeneratedHandlers(");
        source.AppendLine("            this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        source.AppendLine("            global::System.ArgumentNullException.ThrowIfNull(services);");

        foreach (var handler in handlers)
        {
            foreach (var registration in handler.Registrations)
            {
                source.Append("            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddTransient<");
                source.Append(registration.ServiceType);
                source.Append(", ");
                source.Append(handler.ImplementationType);
                source.AppendLine(">(services);");
            }
        }

        source.AppendLine("            return services;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    internal static class SignalynxGeneratedHandlerMap");
        source.AppendLine("    {");
        source.AppendLine("        internal static readonly global::Signalynx.HandlerDescriptor[] Descriptors =");
        source.AppendLine("        {");

        foreach (var handler in handlers)
        {
            foreach (var registration in handler.Registrations)
            {
                source.Append("            new global::Signalynx.HandlerDescriptor(typeof(");
                source.Append(registration.ServiceType);
                source.Append("), typeof(");
                source.Append(handler.ImplementationType);
                source.Append("), ");
                source.Append(registration.AllowsMultiple ? "true" : "false");
                source.AppendLine("),");
            }
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine("        internal static readonly global::System.Collections.Generic.IReadOnlyDictionary<global::System.Type, global::System.Type[]> Handlers =");
        source.AppendLine("            new global::System.Collections.Generic.Dictionary<global::System.Type, global::System.Type[]>");
        source.AppendLine("            {");

        foreach (var group in handlers
                     .SelectMany(static handler => handler.Registrations.Select(registration => (handler, registration)))
                     .GroupBy(static entry => entry.registration.ServiceType, StringComparer.Ordinal)
                     .OrderBy(static group => group.Key, StringComparer.Ordinal))
        {
            source.Append("                [typeof(");
            source.Append(group.Key);
            source.Append(")] = new global::System.Type[] { ");
            source.Append(string.Join(", ", group.Select(static entry => $"typeof({entry.handler.ImplementationType})")));
            source.AppendLine(" },");
        }

        source.AppendLine("            };");
        source.AppendLine("    }");
        source.AppendLine("}");
        context.AddSource("Signalynx.Generated.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static bool IsHandlerInterface(INamedTypeSymbol definition) =>
        definition.ContainingNamespace.ToDisplayString() == "Signalynx" &&
        definition is
        {
            Name: "ICommandHandler",
            Arity: 1 or 2
        } or
        {
            Name: "IQueryHandler" or "IRequestHandler" or "IPipelineBehavior",
            Arity: 2
        } or
        {
            Name: "INotificationHandler" or "IEventHandler",
            Arity: 1
        };

    private static bool IsMultiHandler(INamedTypeSymbol definition) =>
        definition.Name is "INotificationHandler" or "IEventHandler" or "IPipelineBehavior";

    private sealed class HandlerCandidate
    {
        public HandlerCandidate(
            string implementationType,
            ImmutableArray<Registration> registrations,
            Location location)
        {
            ImplementationType = implementationType;
            Registrations = registrations;
            Location = location;
        }

        public string ImplementationType { get; }

        public ImmutableArray<Registration> Registrations { get; }

        public Location Location { get; }
    }

    private sealed class Registration
    {
        public Registration(string serviceType, bool allowsMultiple)
        {
            ServiceType = serviceType;
            AllowsMultiple = allowsMultiple;
        }

        public string ServiceType { get; }

        public bool AllowsMultiple { get; }
    }
}
